//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlamourLights.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlamourLights.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1;7;15
        ///2;4;17
        ///3;22;45.
        /// </summary>
        internal static string department_position {
            get {
                return ResourceManager.GetString("department_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 1;16;10
        ///2;32;20
        ///3;5;2.
        /// </summary>
        internal static string shelves_position {
            get {
                return ResourceManager.GetString("shelves_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a 64;32
        ///0;0;-1
        ///0;1;-1
        ///0;2;-1
        ///0;3;-1
        ///0;4;-1
        ///0;5;-1
        ///0;6;-1
        ///0;7;-1
        ///0;8;-1
        ///0;9;-1
        ///0;10;-1
        ///0;11;-1
        ///0;12;-1
        ///0;13;-1
        ///0;14;-1
        ///0;15;-1
        ///0;16;-1
        ///0;17;-1
        ///0;18;-1
        ///0;19;-1
        ///0;20;-1
        ///0;21;-1
        ///0;22;-1
        ///0;23;-1
        ///0;24;-1
        ///0;25;-1
        ///0;26;-1
        ///0;27;-1
        ///0;28;-1
        ///0;29;-1
        ///0;30;-1
        ///0;31;-1
        ///1;0;-1
        ///1;1;1
        ///1;2;1
        ///1;3;1
        ///1;4;1
        ///1;5;1
        ///1;6;1
        ///1;7;1
        ///1;8;1
        ///1;9;1
        ///1;10;1
        ///1;11;1
        ///1;12;1
        ///1;13;1
        ///1;14;1
        ///1;15;1
        ///1;16;1
        ///1;17;1
        ///1;18;1
        ///1;19;1
        ///1;20;1
        ///1;21;1
        ///1;22;1
        ///1;23;1
        ///1;24;1
        ///1;25;1
        ///1;26;1
        ///1;27;1
        ///1;28;1
        ///1;29 [stringa troncata]&quot;;.
        /// </summary>
        internal static string shop_layout {
            get {
                return ResourceManager.GetString("shop_layout", resourceCulture);
            }
        }
    }
}
